### ISSUE TITLE
can't create index with non root user?

### ISSUE THREAD

**Issue by kensongzhu** [saily/openshift-devpi#1]
Hello, 

I am trying to setup the devpi server on our openshift.  It seems that `--restrict-modify` is  only allowed to` root`. In other words, non root users can't create any index.  Is there anyway to disable or post-update it?

**Comment by saily** [comment]
@kensongzhu this might have been related to https://github.com/devpi/devpi/issues/284, do you still have this issue?

**Comment by saily** [comment]
@kensongzhu this is by purpose configured in the `run.sh` script, see https://github.com/saily/openshift-devpi/blob/master/run.sh#L8. You can build your own image or inject your own `run.sh` script if you have different requirements.
